require 'rubygems'
require 'pathname'
require 'bundler'
require 'rubygems/package_task'
Bundler::GemHelper.install_tasks

require 'rake'
require 'rake/clean'

ROOT = Pathname(__FILE__).dirname.expand_path

# rubocop:disable Style/StringConcatenation
require ROOT + 'lib/do_sqlite3/version'
# rubocop:enable Style/StringConcatenation

SUDO = 'sudo'.freeze unless ENV['SUDOLESS']
BINARY_VERSION = '3071700'.freeze

CLEAN.include(%w({tmp,pkg}/ **/*.{o,so,bundle,jar,log,a,gem,dSYM,obj,pdb,exp,DS_Store,rbc,db} ext/do_sqlite3/Makefile ext-java/target))

FileList['tasks/**/*.rake'].each { |task| import task }
