source "https://rubygems.org"

gem 'rspec', '~> 3.13'
gem 'rspec-its'

gemspec

platforms :jruby do
  gem 'jdbc-mysql', '>=5.0.4'
  gem 'do_jdbc',    '0.10.17'
end

group :development do # Development dependencies (as in the gemspec)
  gem 'rake'
end
