require 'pathname'
require 'rubygems'
require 'bundler'
require 'rubygems/package_task'
Bundler::GemHelper.install_tasks

require 'rake'
require 'rake/clean'

ROOT = Pathname(__FILE__).dirname.expand_path

# rubocop:disable Style/StringConcatenation
require ROOT + 'lib/do_mysql/version'
# rubocop:enable Style/StringConcatenation

SUDO     = 'sudo' unless ENV['SUDOLESS']
BINARY_VERSION = '5.1.65'.freeze

CLEAN.include(%w({tmp,pkg}/ **/*.{o,so,bundle,jar,log,a,gem,dSYM,obj,pdb,exp,DS_Store,rbc,db} ext/do_mysql/Makefile
                 ext-java/target))


# TODO: Workaround for old rspec version

FileList['tasks/**/*.rake'].each { |task| import task }
